/*
 * precompiled.h
 *
 *  Created on: 29.02.2020
 *      Author: doene
 */

#ifndef REPS_HERP_AUTHORIZATIONMODULE_HERP_AUTHORIZATIONMODULE_PRECOMPILED_H_
#define REPS_HERP_AUTHORIZATIONMODULE_HERP_AUTHORIZATIONMODULE_PRECOMPILED_H_

#include <QxOrm.h>
#include <export.h>

#endif /* REPS_HERP_AUTHORIZATIONMODULE_HERP_AUTHORIZATIONMODULE_PRECOMPILED_H_ */
